{% set version = "0.6.4.2" %}

package:
  name: yaml-cpp4rkt
  version: {{ version }}

source:
  url: https://github.com/reaktoro/yaml-cpp4rkt/archive/v{{ version }}.rkt.tar.gz
  sha256: 05b468624de9ed5b1ad0691f09d5b0d19579fc6547b6ed05573408a74461735c

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  commands:
    - test -f $PREFIX/lib/libyaml-cpp${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1  # [win]

about:
  home: https://github.com/reaktoro/yaml-cpp4rkt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'yaml-cpp4rkt is a fork of yaml-cpp to be used in Reaktoro (it exists to produce conda-forge package with most up-to-date version and bug-fixes of yaml-cpp, not yet released by the yaml-cpp team)'
  doc_url: https://github.com/reaktoro/yaml-cpp4rkt
  dev_url: https://github.com/reaktoro/yaml-cpp4rkt

extra:
  recipe-maintainers:
    - allanleal
